### ISSUE TITLE
image_body_parse and image_parse_with_hands

### ISSUE THREAD

**Issue by arhamlet** [benquick123/C-VTON#2]
Can you kindly mention the two models that you have used to create the two folders named  'image_body_parse' and 'image_parse_with_hands' to obtain the labels for the images in the preprocessed-viton dataset. 
Which models have you used to obtain the labels as shown in these two images:
![000001_0](https://user-images.githubusercontent.com/67656492/144417818-e6c2ab11-9349-42fc-a094-51c69367b81d.png)
![000001_0](https://user-images.githubusercontent.com/67656492/144417873-2be8e383-be24-4fa8-a847-7c483bb50430.png)

**Comment by benquick123** [comment]
Hi, sorry for a late reply. In the paper, we've used a DensePose body parser, as well as models and code from [this](https://github.com/kevinlin311tw/CDCL-human-part-segmentation) and [this](https://github.com/PeikeLi/Self-Correction-Human-Parsing) repositories for generation of above images, respectively. Note, that the latter example you posted has an additional labels for neck area (light green on the image) and hands, which we heuristically obtained by subtracting results from body and clothing parser outputs.

Since a significant impairment of the current works lies in the incorrect garment parsing, you might be able to easily obtain better results by finding newer models aiming to solve body and clothing segmentations problems.
