### ISSUE TITLE
preprocessing methods

### ISSUE THREAD

**Issue by Wzj-zju** [benquick123/C-VTON#5]
Can you please provide the preprocessing methods of image_body_parse and image_parse_with_hands.

**Comment by benquick123** [comment]
Hi, I cannot provide you the methods directly, since I don't work on the research position anymore and don't have the access to all the code, but I can clarify on the segmentation preprocessing pipeline. I believe parts of this are also described in the paper.

Essentially, Densepose segmentation model was used for body-part segmentations and paper from [Liu et al.](https://arxiv.org/abs/1910.09777) for clothing segmentations. Then, if neccessary, the body-part of clothing masks from two models were combined to get the final (provided) segmentations. I am not sure if that helps you, but these two models should suffice for generation of all segmentations used in the paper.
